CREATE TABLE "accepted_tokens" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" varchar(20) NOT NULL,
	"name" varchar NOT NULL,
	"mint_address" varchar NOT NULL,
	"decimals" integer DEFAULT 9 NOT NULL,
	"logo_url" text,
	"tier" varchar(20) NOT NULL,
	"allowed_for_access" boolean DEFAULT false,
	"allowed_for_licensing" boolean DEFAULT false,
	"is_active" boolean DEFAULT false,
	"activated_at" timestamp,
	"deactivated_at" timestamp,
	"price_source" varchar(50),
	"last_price_usd" varchar,
	"last_price_updated_at" timestamp,
	"community_website" text,
	"community_twitter" varchar,
	"community_telegram" varchar,
	"community_discord" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "accepted_tokens_symbol_unique" UNIQUE("symbol"),
	CONSTRAINT "accepted_tokens_mint_address_unique" UNIQUE("mint_address")
);
--> statement-breakpoint
CREATE TABLE "admin_secrets" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"encrypted_value" text NOT NULL,
	"iv" varchar(64) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "admin_secrets_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "authorized_usages" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"logo_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"usage_url" text NOT NULL,
	"usage_type" varchar(50),
	"usage_platform" varchar(100),
	"is_verified" boolean DEFAULT false,
	"verified_at" timestamp,
	"last_scanned" timestamp,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "code_repo_snapshots" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"asset_id" varchar,
	"repo_url" text NOT NULL,
	"repo_name" text NOT NULL,
	"repo_owner" text NOT NULL,
	"commit_hash" varchar(40) NOT NULL,
	"commit_message" text,
	"commit_author" text,
	"committed_at" timestamp,
	"branch_name" varchar(100),
	"tag_name" varchar(100),
	"manifest_hash" varchar(64),
	"manifest_uri" text,
	"bundle_hash" varchar(64),
	"bundle_uri" text,
	"file_count" integer,
	"total_lines_of_code" integer,
	"languages" jsonb,
	"metadata_ipfs_hash" varchar(100),
	"nft_address" varchar,
	"transaction_hash" varchar,
	"minted_at" timestamp,
	"status" varchar(20) DEFAULT 'pending',
	"registered_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "collections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"symbol" varchar(10),
	"company_name" varchar NOT NULL,
	"copyright_year" integer,
	"collection_address" varchar,
	"transaction_hash" varchar,
	"explorer_url" text,
	"ipfs_metadata_hash" varchar(100),
	"nft_metadata_json" jsonb,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"minted_at" timestamp,
	"is_public" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "compliance_cases" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_number" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"triggering_log_ids" text[],
	"case_type" varchar(30) NOT NULL,
	"triggers_activated" text[],
	"total_amount" varchar,
	"evidence_attached" jsonb,
	"rule_snapshot" jsonb,
	"status" varchar(30) DEFAULT 'open' NOT NULL,
	"decision" varchar(30),
	"decision_reason" text,
	"decision_made_by" varchar,
	"decision_made_at" timestamp,
	"assigned_to" varchar,
	"assigned_at" timestamp,
	"priority" varchar(10) DEFAULT 'medium' NOT NULL,
	"due_date" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "compliance_cases_case_number_unique" UNIQUE("case_number")
);
--> statement-breakpoint
CREATE TABLE "compliance_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tx_signature" varchar,
	"slot" integer,
	"block_time" timestamp,
	"program_id" varchar,
	"instruction_type" varchar(50),
	"buyer_address" varchar,
	"seller_address" varchar,
	"escrow_address" varchar,
	"token_mint" varchar,
	"token_type" varchar(10),
	"amount" varchar,
	"usd_value" varchar,
	"pricing_source" varchar,
	"platform_fee" varchar,
	"network_fee" varchar,
	"triggers_activated" text[],
	"trigger_details" jsonb,
	"kyc_tier_required" varchar(10),
	"user_id" varchar,
	"user_kyc_tier" varchar(10),
	"action_taken" varchar(50),
	"reviewer_id" varchar,
	"review_notes" text,
	"reviewed_at" timestamp,
	"case_id" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "compliance_trigger_rules" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"trigger_code" varchar(50) NOT NULL,
	"name" varchar NOT NULL,
	"description" text,
	"category" varchar(30) NOT NULL,
	"threshold_value" varchar,
	"threshold_period_days" integer,
	"threshold_count" integer,
	"threshold_multiplier" varchar,
	"threshold_percentage" integer,
	"required_tier" varchar(10) NOT NULL,
	"requires_documents" boolean DEFAULT false,
	"requires_manual_review" boolean DEFAULT false,
	"severity" varchar(20) DEFAULT 'medium' NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "compliance_trigger_rules_trigger_code_unique" UNIQUE("trigger_code")
);
--> statement-breakpoint
CREATE TABLE "contract_bindings" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"logo_id" varchar NOT NULL,
	"contract_address" varchar NOT NULL,
	"chain_id" integer DEFAULT 1 NOT NULL,
	"verification_level" varchar DEFAULT 'standard' NOT NULL,
	"prelaunch_registration" boolean DEFAULT false NOT NULL,
	"deployment_date" timestamp,
	"deployment_tx_hash" varchar,
	"ipfs_proof_url" varchar,
	"binding_date" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "copycat_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"logo_id" varchar NOT NULL,
	"report_type" varchar DEFAULT 'token' NOT NULL,
	"copycat_contract_address" varchar,
	"copycat_ticker" varchar,
	"copycat_name" varchar,
	"chain_id" integer DEFAULT 1 NOT NULL,
	"copycat_twitter" text,
	"copycat_telegram" text,
	"copycat_website" text,
	"copycat_tiktok" text,
	"copycat_facebook" text,
	"copycat_instagram" text,
	"copycat_discord" text,
	"found_on_platform" varchar,
	"found_on_url" text,
	"screenshot_url" text,
	"evidence_description" text,
	"evidence_url" text,
	"similarity_score" integer,
	"status" varchar DEFAULT 'pending' NOT NULL,
	"submitted_to_orgs" text[],
	"registration_number" varchar,
	"registration_date" timestamp,
	"ipfs_proof_url" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ip_assets" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"asset_type" varchar(20) NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"sha256" varchar(64) NOT NULL,
	"primary_uri" text,
	"manifest_uri" text,
	"thumbnail_uri" text,
	"ownership_claimed_at" timestamp,
	"ownership_description" text,
	"copyright_status" varchar(20) DEFAULT 'none',
	"trademark_status" varchar(20) DEFAULT 'none',
	"nft_address" varchar,
	"transaction_hash" varchar,
	"minted_at" timestamp,
	"rights_holders" jsonb,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"registered_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "kyc_status" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"tier" varchar(10) DEFAULT '0' NOT NULL,
	"id_verification_status" varchar(20),
	"id_verification_vendor" varchar,
	"id_verification_reference" varchar,
	"id_verified_at" timestamp,
	"sanctions_status" varchar(20),
	"sanctions_list_version" varchar,
	"sanctions_screened_at" timestamp,
	"pep_status" varchar(20),
	"risk_tier" varchar(20),
	"risk_reason_codes" text[],
	"risk_assessed_at" timestamp,
	"source_of_funds" varchar(50),
	"source_of_funds_verified" boolean DEFAULT false,
	"deal_document_hash" varchar,
	"deal_document_uploaded_at" timestamp,
	"sanctions_attestation_at" timestamp,
	"tos_version" varchar,
	"tos_accepted_at" timestamp,
	"daily_limit" varchar,
	"monthly_limit" varchar,
	"single_tx_limit" varchar,
	"rolling_30_day_volume" varchar DEFAULT '0',
	"last_30_day_volume_updated_at" timestamp,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"status_reason" text,
	"manual_review_required" boolean DEFAULT false,
	"manual_review_notes" text,
	"last_reviewed_by" varchar,
	"last_reviewed_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "kyc_status_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "license_contracts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"licensor_user_id" varchar NOT NULL,
	"licensor_wallet" varchar NOT NULL,
	"licensee_wallet" varchar NOT NULL,
	"licensee_email" varchar,
	"licensee_name" varchar,
	"logo_id" varchar,
	"asset_id" varchar,
	"license_type" varchar(30) NOT NULL,
	"template_used" varchar(50),
	"platform_bitmap" integer DEFAULT 0 NOT NULL,
	"other_platforms" text,
	"can_transfer" boolean DEFAULT false NOT NULL,
	"can_sublicense" boolean DEFAULT false NOT NULL,
	"can_modify" boolean DEFAULT false NOT NULL,
	"requires_attribution" boolean DEFAULT true NOT NULL,
	"permitted_wallets" text[],
	"geographic_scope" varchar(50) DEFAULT 'worldwide',
	"geographic_details" text,
	"usage_purpose" varchar(30) DEFAULT 'both',
	"scope_of_use_description" text,
	"scope_of_use_category" varchar(50),
	"specific_usage_context" text,
	"content_restrictions" text[],
	"content_restrictions_custom" text,
	"edit_restrictions" text[],
	"edit_restrictions_custom" text,
	"min_display_size" varchar(20),
	"approval_required" boolean DEFAULT false,
	"approval_process" text,
	"approval_timeframe_days" integer,
	"credit_requirements" text,
	"credit_placement" varchar(50),
	"quality_standards" text,
	"brand_guidelines_url" text,
	"is_perpetual" boolean DEFAULT false NOT NULL,
	"duration_days" integer,
	"starts_at" timestamp,
	"expires_at" timestamp,
	"is_exclusivity_time_limited" boolean DEFAULT false,
	"exclusivity_ends_at" timestamp,
	"has_revenue_share" boolean DEFAULT false,
	"royalty_percentage" varchar,
	"payment_terms_hash" varchar(100),
	"upfront_payment_amount" varchar,
	"upfront_payment_currency" varchar(10),
	"mfn_clause_enabled" boolean DEFAULT false,
	"payment_schedule" jsonb,
	"payment_schedule_type" varchar(30),
	"minimum_guarantee" varchar,
	"minimum_guarantee_currency" varchar(10),
	"performance_bonus" text,
	"auto_renew" boolean DEFAULT false,
	"renewal_notice_days" integer DEFAULT 30,
	"revocation_conditions" text,
	"arbitration_agreed" boolean DEFAULT false NOT NULL,
	"indemnification_agreed" boolean DEFAULT false NOT NULL,
	"custom_terms" text,
	"custom_terms_hash" varchar(100),
	"licensor_signed_at" timestamp,
	"licensor_signature" varchar,
	"licensee_signed_at" timestamp,
	"licensee_signature" varchar,
	"licensor_ip_address" varchar(50),
	"licensor_device_info" text,
	"licensee_ip_address" varchar(50),
	"licensee_device_info" text,
	"intent_to_be_binding_acknowledged" boolean DEFAULT false,
	"electronic_transaction_consent" boolean DEFAULT false,
	"terms_read_acknowledged" boolean DEFAULT false,
	"iscl_version" varchar(10) DEFAULT '1.0.0',
	"iscl_template_id" varchar(50),
	"pda_address" varchar,
	"contract_address" varchar,
	"transaction_hash" varchar,
	"minted_at" timestamp,
	"metadata_ipfs_hash" varchar(100),
	"badge_image_arweave_url" text,
	"badge_image_ipfs_hash" varchar(100),
	"image_color_palette" text[],
	"image_dominant_color" varchar(7),
	"image_pantone_colors" text[],
	"image_created_at" timestamp,
	"license_issued_at" timestamp,
	"license_type_description" text,
	"current_holder_name" varchar,
	"current_holder_wallet" varchar,
	"current_holder_email" varchar,
	"holder_transfer_history" jsonb,
	"jurisdiction_code" varchar(10) DEFAULT 'US',
	"jurisdiction_version" varchar(10) DEFAULT '1.0',
	"governing_law" varchar,
	"dispute_venue" varchar,
	"gdpr_compliant" boolean DEFAULT false,
	"gdpr_data_processing_agreed" boolean DEFAULT false,
	"gdpr_withdrawal_rights_acknowledged" boolean DEFAULT false,
	"pipeda_compliant" boolean DEFAULT false,
	"pdpa_compliant" boolean DEFAULT false,
	"appi_compliant" boolean DEFAULT false,
	"moral_rights_waived" boolean DEFAULT false,
	"bilingual_required" boolean DEFAULT false,
	"vat_statement" text,
	"regional_clauses" jsonb,
	"p2p_sender_wallet" varchar,
	"p2p_receiver_wallet" varchar,
	"p2p_transaction_hash" varchar,
	"p2p_transaction_amount" varchar,
	"p2p_transaction_currency" varchar(10),
	"p2p_transaction_note" text,
	"p2p_transaction_linked_at" timestamp,
	"shareable_slug" varchar(50),
	"creation_fee" varchar DEFAULT '0.025' NOT NULL,
	"creation_fee_paid" boolean DEFAULT false,
	"creation_fee_payment_tx" varchar,
	"creation_fee_paid_at" timestamp,
	"status" varchar(30) DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "license_contracts_shareable_slug_unique" UNIQUE("shareable_slug")
);
--> statement-breakpoint
CREATE TABLE "logos" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"collection_id" varchar,
	"asset_id" varchar,
	"file_name" text NOT NULL,
	"image_url" text,
	"user_wallet_storage_path" text,
	"file_size" integer NOT NULL,
	"mime_type" varchar NOT NULL,
	"file_hash" varchar NOT NULL,
	"ipfs_hash" varchar(100),
	"ipfs_metadata_hash" varchar(100),
	"verified_ipfs_hash" varchar(100),
	"arweave_url" text,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"format" varchar NOT NULL,
	"color_palette" text[],
	"dominant_color" varchar,
	"registration_type" varchar(20),
	"registration_data" jsonb,
	"token_name" text,
	"token_ticker" varchar(20),
	"launch_platform" varchar(50),
	"launch_timeline" varchar(50),
	"token_contract_address" varchar(100),
	"token_contract_chain" varchar(20),
	"token_contract_added_at" timestamp,
	"token_pool_address" varchar(100),
	"verified_media_versions" jsonb,
	"ticker_verification_urls" text[],
	"ticker_verified" boolean DEFAULT false,
	"ticker_verification_started_at" timestamp,
	"ticker_verification_deadline" timestamp,
	"bot_verification_status" varchar(20),
	"smart_contract_hash" varchar,
	"smart_contract_created_at" timestamp,
	"thumbnail_url" text,
	"thumbnail_size" integer,
	"ownership_claimed_at" timestamp DEFAULT now() NOT NULL,
	"ownership_description" text,
	"intended_use" text,
	"copyright_status" varchar(50),
	"copyright_application_number" varchar,
	"copyright_filing_date" timestamp,
	"trademark_status" varchar(50),
	"trademark_application_number" varchar,
	"trademark_filing_date" timestamp,
	"patent_status" varchar(50),
	"patent_application_number" varchar,
	"patent_filing_date" timestamp,
	"description" text,
	"tags" text[],
	"nft_address" varchar,
	"minted_at" timestamp,
	"transaction_hash" varchar,
	"blockchain_metadata_json" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "music_collections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"asset_id" varchar,
	"name" text NOT NULL,
	"description" text,
	"label_name" varchar,
	"cover_art_uri" text,
	"cover_art_hash" varchar(64),
	"contact_email" varchar,
	"website" text,
	"metadata_ipfs_hash" varchar(100),
	"is_public" boolean DEFAULT true,
	"status" varchar(20) DEFAULT 'active',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	"category" varchar NOT NULL,
	"platform" varchar,
	"contact_email" text,
	"dmca_email" text,
	"contact_phone" varchar,
	"support_url" text,
	"submission_url" text,
	"api_endpoint" text,
	"response_time" varchar,
	"requires_legal_name" boolean DEFAULT false,
	"requires_registration_number" boolean DEFAULT false,
	"accepted_documents" text[],
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "organizations_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "outreach_letters" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_id" varchar NOT NULL,
	"organization_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"template_type" varchar NOT NULL,
	"letter_subject" text NOT NULL,
	"letter_body" text NOT NULL,
	"user_contact_name" varchar,
	"user_contact_email" varchar,
	"user_contact_phone" varchar,
	"user_company_name" varchar,
	"sent_at" timestamp,
	"sent_via" varchar,
	"response_received" boolean DEFAULT false,
	"response_date" timestamp,
	"response_notes" text,
	"status" varchar DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"collection_id" varchar,
	"logo_id" varchar,
	"transaction_signature" varchar,
	"from_wallet" varchar NOT NULL,
	"to_wallet" varchar NOT NULL,
	"amount" varchar NOT NULL,
	"token_type" varchar(10) NOT NULL,
	"status" varchar(20) NOT NULL,
	"payment_type" varchar(20) NOT NULL,
	"logo_count" integer,
	"pricing_tier" varchar(50),
	"rental_months" integer,
	"block_number" integer,
	"confirmed_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "payments_transaction_signature_unique" UNIQUE("transaction_signature")
);
--> statement-breakpoint
CREATE TABLE "platform_config" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" varchar(100) NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"updated_by" varchar,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "platform_config_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "quiz_attempts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"telegram_user_id" varchar,
	"telegram_username" varchar,
	"telegram_first_name" varchar,
	"question_id" varchar NOT NULL,
	"user_answer" text NOT NULL,
	"is_correct" boolean NOT NULL,
	"points_earned" integer NOT NULL,
	"cath_reward" varchar,
	"hint_used" boolean DEFAULT false,
	"points_before_hint" integer,
	"time_to_answer" integer,
	"battle_id" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "quiz_questions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"category" varchar(100) NOT NULL,
	"difficulty" varchar(20) NOT NULL,
	"points" integer NOT NULL,
	"question" text NOT NULL,
	"options" text[] NOT NULL,
	"answer" text NOT NULL,
	"hint" text,
	"explanation" text,
	"source_authority" varchar(50),
	"source_url" text,
	"source_citation" text,
	"round_number" integer,
	"question_order" integer,
	"usage_count" integer DEFAULT 0,
	"correct_count" integer DEFAULT 0,
	"hint_usage_count" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "quiz_stats" (
	"user_id" varchar PRIMARY KEY NOT NULL,
	"telegram_user_id" varchar,
	"telegram_username" varchar,
	"telegram_first_name" varchar,
	"total_questions" integer DEFAULT 0 NOT NULL,
	"correct_answers" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"total_cath_earned" varchar DEFAULT '0',
	"daily_points" integer DEFAULT 0 NOT NULL,
	"daily_correct_answers" integer DEFAULT 0 NOT NULL,
	"daily_questions_answered" integer DEFAULT 0 NOT NULL,
	"last_daily_reset" timestamp DEFAULT now(),
	"streak" integer DEFAULT 0,
	"longest_streak" integer DEFAULT 0,
	"last_quiz_at" timestamp,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "referral_tracking" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"referrer_user_id" varchar NOT NULL,
	"referred_user_id" varchar NOT NULL,
	"referral_code" varchar NOT NULL,
	"signed_up_at" timestamp DEFAULT now(),
	"activated_at" timestamp,
	"referrer_reward_amount" varchar,
	"referrer_reward_paid_at" timestamp,
	"referred_bonus_amount" varchar,
	"referred_bonus_paid_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "release_tracks" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"release_id" varchar NOT NULL,
	"track_id" varchar NOT NULL,
	"disc_number" integer DEFAULT 1 NOT NULL,
	"track_number" integer NOT NULL,
	"hybrid_id" varchar(64) NOT NULL,
	"display_title" text,
	"display_artist" text,
	"release_isrc" varchar(12),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "releases" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"asset_id" varchar,
	"collection_id" varchar,
	"title" text NOT NULL,
	"artist_name" text NOT NULL,
	"release_type" varchar(20) NOT NULL,
	"cover_art_uri" text,
	"cover_art_hash" varchar(64),
	"release_date" timestamp,
	"genre" varchar(50),
	"sub_genre" varchar(50),
	"language" varchar(10),
	"upc" varchar(14),
	"catalog_number" varchar(50),
	"label_name" varchar,
	"copyright_line" text,
	"production_line" text,
	"metadata_ipfs_hash" varchar(100),
	"nft_address" varchar,
	"transaction_hash" varchar,
	"minted_at" timestamp,
	"status" varchar(20) DEFAULT 'draft',
	"registered_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "rewards_log" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"action_type" varchar(50) NOT NULL,
	"base_amount" varchar NOT NULL,
	"multiplier" integer DEFAULT 1 NOT NULL,
	"final_amount" varchar NOT NULL,
	"related_entity_id" varchar,
	"related_entity_type" varchar(30),
	"referred_user_id" varchar,
	"social_platform" varchar(30),
	"social_post_url" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telegram_leaderboard" (
	"telegram_user_id" varchar PRIMARY KEY NOT NULL,
	"telegram_username" varchar,
	"telegram_first_name" varchar,
	"total_questions" integer DEFAULT 0 NOT NULL,
	"correct_answers" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"total_experience" integer DEFAULT 0 NOT NULL,
	"daily_points" integer DEFAULT 0 NOT NULL,
	"daily_experience" integer DEFAULT 0 NOT NULL,
	"daily_correct_answers" integer DEFAULT 0 NOT NULL,
	"daily_questions_answered" integer DEFAULT 0 NOT NULL,
	"last_daily_reset" timestamp DEFAULT now(),
	"streak" integer DEFAULT 0,
	"longest_streak" integer DEFAULT 0,
	"last_quiz_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "token_applications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" varchar(20) NOT NULL,
	"name" varchar NOT NULL,
	"mint_address" varchar NOT NULL,
	"decimals" integer DEFAULT 9 NOT NULL,
	"logo_url" text,
	"website" text,
	"twitter" varchar,
	"telegram" varchar,
	"discord" varchar,
	"token_age_months" integer,
	"daily_volume" varchar,
	"holder_count" integer,
	"applicant_user_id" varchar,
	"applicant_email" varchar,
	"applicant_notes" text,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"reviewed_by" varchar,
	"reviewed_at" timestamp,
	"review_notes" text,
	"rejection_reason" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "tracks" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"asset_id" varchar,
	"collection_id" varchar,
	"title" text NOT NULL,
	"artist_name" text NOT NULL,
	"featured_artists" text[],
	"audio_hash_sha256" varchar(64) NOT NULL,
	"preview_hash_sha256" varchar(64),
	"context_hash_sha256" varchar(64) NOT NULL,
	"manifest_uri" text NOT NULL,
	"audio_encrypted_uri" text NOT NULL,
	"preview_uri" text NOT NULL,
	"file_name" text NOT NULL,
	"file_size" integer NOT NULL,
	"mime_type" varchar(50) NOT NULL,
	"duration_ms" integer,
	"sample_rate" integer,
	"bit_depth" integer,
	"channels" integer,
	"is_explicit" boolean DEFAULT false,
	"bpm" integer,
	"key" varchar(10),
	"waveform_data" jsonb,
	"cover_uri" text,
	"metadata_ipfs_hash" varchar(100),
	"isrc" varchar(12),
	"iswc" varchar(15),
	"publisher_name" text,
	"writer_credits" jsonb,
	"rights_holders" jsonb,
	"registration_type" varchar(20),
	"original_track_id" varchar,
	"nft_address" varchar,
	"transaction_hash" varchar,
	"minted_at" timestamp,
	"status" varchar(20) DEFAULT 'active',
	"registered_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "treasury_wallets" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role" varchar(20) NOT NULL,
	"name" varchar NOT NULL,
	"address" varchar NOT NULL,
	"domain_name" varchar,
	"purpose" text,
	"network" varchar(20) DEFAULT 'devnet' NOT NULL,
	"sweep_enabled" boolean DEFAULT false,
	"sweep_threshold" varchar,
	"sweep_schedule" varchar,
	"sweep_destination" varchar,
	"last_sweep_at" timestamp,
	"last_sweep_amount" varchar,
	"last_sweep_tx_hash" varchar,
	"required_signatures" integer DEFAULT 2,
	"authorized_signers" text[],
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"last_balance_check" timestamp,
	"cached_balance" varchar,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "treasury_wallets_address_unique" UNIQUE("address")
);
--> statement-breakpoint
CREATE TABLE "used_transactions" (
	"tx_hash" varchar PRIMARY KEY NOT NULL,
	"user_id" varchar,
	"purpose" varchar(30) NOT NULL,
	"amount" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"wallet_address" varchar,
	"wallet_verified" boolean DEFAULT false,
	"email_verified" boolean DEFAULT false,
	"email_verification_token" varchar,
	"email_verification_token_expires_at" timestamp,
	"wallet_type" varchar(20),
	"wallet_name" varchar(50),
	"custom_name" varchar(32),
	"solana_public_key" varchar,
	"solana_encrypted_private_key" text,
	"wallet_salt" varchar,
	"solana_wallet_created_at" timestamp,
	"wallet_funding_tx_hash" varchar,
	"ceremony_completed" boolean DEFAULT false,
	"ceremony_stages" jsonb,
	"recovery_phrase_verified" boolean DEFAULT false,
	"verification_attempts" integer DEFAULT 0,
	"terms_accepted_at" timestamp,
	"has_exported_private_key" boolean DEFAULT false,
	"encrypted_recovery_phrase" text,
	"recovery_phrase_shown_at" timestamp,
	"twitter_handle" varchar,
	"telegram_handle" varchar,
	"discord_handle" varchar,
	"instagram_handle" varchar,
	"telegram_group_link" varchar,
	"website_url" varchar,
	"bio" text,
	"notify_payments_due" boolean DEFAULT true,
	"notify_rental_reminders" boolean DEFAULT true,
	"account_status" varchar(20) DEFAULT 'pending',
	"is_admin" boolean DEFAULT false,
	"subscription_tier" varchar(20),
	"subscription_expires_at" timestamp,
	"subscription_payment_tx" varchar,
	"subscription_paid_at" timestamp,
	"subscription_price_paid" varchar,
	"was_promo_price" boolean DEFAULT false,
	"pending_license_fee" varchar,
	"pending_license_fee_count" integer DEFAULT 0,
	"total_license_fee_paid" varchar DEFAULT '0',
	"sltr_balance" varchar DEFAULT '0',
	"sltr_total_earned" varchar DEFAULT '0',
	"sltr_claimed_amount" varchar DEFAULT '0',
	"last_sltr_claim_at" timestamp,
	"early_adopter_multiplier" integer DEFAULT 1,
	"referral_code" varchar(20),
	"referred_by" varchar,
	"referral_count" integer DEFAULT 0,
	"referral_rewards_earned" varchar DEFAULT '0',
	"profile_completed_at" timestamp,
	"socials_linked_at" timestamp,
	"first_image_uploaded_at" timestamp,
	"is_discoverable" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_referral_code_unique" UNIQUE("referral_code")
);
--> statement-breakpoint
CREATE TABLE "variation_protections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"logo_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"original_ticker" varchar NOT NULL,
	"original_name" varchar,
	"variation_ticker" varchar,
	"variation_name" varchar,
	"variation_type" varchar,
	"is_auto_generated" boolean DEFAULT false,
	"is_approved" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "visitor_accounts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar NOT NULL,
	"email_verified" boolean DEFAULT false,
	"verification_token" varchar,
	"verification_token_expires_at" timestamp,
	"session_token" varchar,
	"pending_solt_rewards" varchar DEFAULT '0',
	"pending_game_points" integer DEFAULT 0,
	"pending_experience_points" integer DEFAULT 0,
	"current_streak" integer DEFAULT 0,
	"highest_streak" integer DEFAULT 0,
	"questions_answered" integer DEFAULT 0,
	"correct_answers" integer DEFAULT 0,
	"last_login_at" timestamp DEFAULT now(),
	"rewards_expire_at" timestamp,
	"marketing_opt_in" boolean DEFAULT false,
	"converted_to_user_id" varchar,
	"converted_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "visitor_accounts_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "authorized_usages" ADD CONSTRAINT "authorized_usages_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "authorized_usages" ADD CONSTRAINT "authorized_usages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code_repo_snapshots" ADD CONSTRAINT "code_repo_snapshots_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code_repo_snapshots" ADD CONSTRAINT "code_repo_snapshots_asset_id_ip_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."ip_assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "collections" ADD CONSTRAINT "collections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compliance_cases" ADD CONSTRAINT "compliance_cases_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compliance_cases" ADD CONSTRAINT "compliance_cases_decision_made_by_users_id_fk" FOREIGN KEY ("decision_made_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compliance_cases" ADD CONSTRAINT "compliance_cases_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compliance_logs" ADD CONSTRAINT "compliance_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compliance_logs" ADD CONSTRAINT "compliance_logs_reviewer_id_users_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_bindings" ADD CONSTRAINT "contract_bindings_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "copycat_reports" ADD CONSTRAINT "copycat_reports_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "copycat_reports" ADD CONSTRAINT "copycat_reports_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ip_assets" ADD CONSTRAINT "ip_assets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kyc_status" ADD CONSTRAINT "kyc_status_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kyc_status" ADD CONSTRAINT "kyc_status_last_reviewed_by_users_id_fk" FOREIGN KEY ("last_reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "license_contracts" ADD CONSTRAINT "license_contracts_licensor_user_id_users_id_fk" FOREIGN KEY ("licensor_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "license_contracts" ADD CONSTRAINT "license_contracts_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "logos" ADD CONSTRAINT "logos_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "logos" ADD CONSTRAINT "logos_collection_id_collections_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "music_collections" ADD CONSTRAINT "music_collections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "music_collections" ADD CONSTRAINT "music_collections_asset_id_ip_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."ip_assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_letters" ADD CONSTRAINT "outreach_letters_report_id_copycat_reports_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."copycat_reports"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_letters" ADD CONSTRAINT "outreach_letters_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_letters" ADD CONSTRAINT "outreach_letters_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_collection_id_collections_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_config" ADD CONSTRAINT "platform_config_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_question_id_quiz_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."quiz_questions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz_stats" ADD CONSTRAINT "quiz_stats_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_tracking" ADD CONSTRAINT "referral_tracking_referrer_user_id_users_id_fk" FOREIGN KEY ("referrer_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_tracking" ADD CONSTRAINT "referral_tracking_referred_user_id_users_id_fk" FOREIGN KEY ("referred_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "release_tracks" ADD CONSTRAINT "release_tracks_release_id_releases_id_fk" FOREIGN KEY ("release_id") REFERENCES "public"."releases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "release_tracks" ADD CONSTRAINT "release_tracks_track_id_tracks_id_fk" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "releases" ADD CONSTRAINT "releases_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "releases" ADD CONSTRAINT "releases_asset_id_ip_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."ip_assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "releases" ADD CONSTRAINT "releases_collection_id_music_collections_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."music_collections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rewards_log" ADD CONSTRAINT "rewards_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_applications" ADD CONSTRAINT "token_applications_applicant_user_id_users_id_fk" FOREIGN KEY ("applicant_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_applications" ADD CONSTRAINT "token_applications_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_asset_id_ip_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."ip_assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_collection_id_music_collections_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."music_collections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "treasury_wallets" ADD CONSTRAINT "treasury_wallets_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "used_transactions" ADD CONSTRAINT "used_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "variation_protections" ADD CONSTRAINT "variation_protections_logo_id_logos_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."logos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "variation_protections" ADD CONSTRAINT "variation_protections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "visitor_accounts" ADD CONSTRAINT "visitor_accounts_converted_to_user_id_users_id_fk" FOREIGN KEY ("converted_to_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");